#!/usr/bin/env bash

# Exited with 67: Bu paketin içeriği modifiye edilmiş, bunu bu şekilde kullanmamalısın.
# Exited with 1: Usually related with the system itself, nothing to do

dpkg_path="/var/lib/dpkg/info/org.favour.nowatusialert.list"
echo -e "--------------------------------------------\nAppleFavour © 2023\n--------------------------------------------"

if [[ $dpkg_path == "" ]];then
    echo -e "==> This package modified! Interrupting installer...\n==> Remove this package reinstall from its source."
    exit 67
    else
    if killall -9 WhatsApp 2>/dev/null ;then
    echo -e "==> Quitting application net.whatsapp.Whatsapp'...\n==> Application 'net.whatsapp.Whatsapp' quit successfully."
    else
    echo -e "==> Application 'net.whatsapp.Whatsapp' did not quit."
fi;fi

echo -e "--------------------------------------------"